---
name: ubuntu-{system.release}-{system.architecture}-{%y}{%m}{%d}
provider:
  name: virtualbox
  guest_additions: /usr/share/virtualbox/VBoxGuestAdditions.iso
bootstrapper:
  include_packages:
    - initramfs-tools
    - iproute2
    - iputils-ping
    - isc-dhcp-client
    - isc-dhcp-common
    - net-tools
    - netbase
    - resolvconf
    - sudo
    - udev
  workspace: /tmp
  variant: minbase
system:
  release: xenial
  architecture: amd64
  bootloader: grub
  charmap: UTF-8
  hostname: localhost
  locale: C
  timezone: UTC
volume:
  backing: vmdk
  partitions:
    type: msdos
    boot:
      filesystem: ext2
      size: 128MiB
    root:
      filesystem: ext4
      size: 1792MiB
    swap:
      size: 128MiB
packages: {}
plugins:
  root_password:
    password: test
  minimize_size:
    apt:
      autoclean: true
      languages: [none]
      gzip_indexes: true
      autoremove_suggests: true
    dpkg:
      locales: []
      exclude_docs: true
  vagrant: {}
